# IBM collection namespace
namespace: ibm

# IBM z/OS core collection as part of the
# Red Hat Ansible Certified Content for IBM Z offering
name: ibm_zos_core

# The collection version
version: 1.10.0-beta.1

# Collection README file
readme: README.md

# Contributors
authors:
  - Demetrios Dimatos <ddimatos@us.ibm.com>
  - Rich Parker <richp@ibm.com>
  - Ketan Kelkar <ketan.kelkar@ibm.com>
  - Ivan Moreno <ivan.moreno.soto@ibm.com>
  - Oscar Fernando Flores Garcia <fernando.flores@ibm.com>
  - Jenny Huang <jennyhuang@ibm.com>
  - Marcel Gutierrez <andre.marcel.gutierrez@ibm.com>

# Description
description: The IBM z/OS core collection includes connection plugins, action plugins, modules, filters and ansible-doc to automate tasks on z/OS.

# Portions of this collection are licensed under GNU General Public License Version 3.0
# and portions of this collection are licensed under Apache License, Version 2.0
license:
  - "GPL-3.0-only"
  - "Apache-2.0"

# Tags
tags:
  [
    ibm,
    z,
    zos,
    z_os,
    core,
    zos_core,
    ibm_zos_core,
    data_set,
    jcl,
    uss,
    mvs,
    infrastructure,
  ]

# Collections that this collection requires to be installed for it to be usable.
# dependencies: { # This collection depends on no other collections # }

# The URL of the originating SCM repository
repository: https://github.com/ansible-collections/ibm_zos_core

# The URL to any online docs
documentation: https://ibm.github.io/z_ansible_collections_doc/index.html

# The URL to the homepage of the collection/project
homepage: https://www.ibm.com/support/z-content-solutions/ansible/

# The URL to the collection issue tracker
issues: https://github.com/ansible-collections/ibm_zos_core/issues

# Ignore files and directories matching the following patterns
build_ignore:
  - '*.tar.gz'
  - __pycache__
  - .cache
  - .DS_Store
  - .git
  - .github
  - .gitignore
  - .python-version
  - .pytest_cache
  - .vscode
  - Jenkinsfile
  - ac
  - ansible.cfg
  - changelogs
  - collections
  - docs
  - importer_result.json
  - scripts
  - test_config.yml
  - tests/*.ini
  - tests/*.py
  - tests/.pytest_cache
  - tests/__pycache__
  - tests/functional
  - tests/helpers
  - tests/requirements.txt
  - tests/unit
  - tests/sanity/ignore-2.9.txt
  - tests/sanity/ignore-2.10.txt
  - tests/sanity/ignore-2.11.txt
  - tests/sanity/ignore-2.12.txt
  - tests/sanity/ignore-2.13.txt
  - tests/sanity/ignore-2.14.txt
  - venv*
