# IBM collection namespace
namespace: ibm

# Red Hat Ansible Certified Content for IBM Z
name: ibm_zos_core 

# The collection version
version: 0.0.4

# Collection README file
readme: README.md

# Contributors
authors:
  - Asif Mahmud <asif.mahmud@ibm.com>
  - Blake Becker <blake.becker@ibm.com>
  - Xiao Yuan Ma <bjmaxy@cn.ibm.com>
  - Demetrios Dimatos <ddimatos@us.ibm.com>
  - Jack Ho <jack.ho@ibm.com>
  - Lu Zhao <zlbjlu@cn.ibm.com>
  - Ping Xiao <xiaoping@cn.ibm.com>

# Description
description: The Red Hat Ansible Certified Content for IBM Z core collection includes connection plugins, action plugins, modules and sample playbooks to automate tasks on Z such as creating data sets, retrieving job output, and submitting jobs.

# Portions of this collection are licensed under GNU General Public License Version 3.0
# and portions of this collection are licensed under Apache License, Version 2.0
license:
   - "GPL-3.0-only"
   - "Apache-2.0"

# Tags
tags: [ibm,z,zos,z_os,core,zos_core,red_hat_ansible_certified_cotent_for_ibm_z,data_set,jcl,uss,mvs] 

# Collections that this collection requires to be installed for it to be usable.
# dependencies: {} # This collection depends on no other collections

# The URL of the originating SCM repository
repository: https://github.com/ansible-collections/ibm_zos_core

# The URL to any online docs
documentation: https://github.com/ansible-collections/ibm_zos_core/wiki 

# The URL to the homepage of the collection/project
# homepage: https://www.ibm.com/it-infrastructure/z/

# The URL to the collection issue tracker
issues: https://github.com/ansible-collections/ibm_zos_core/issues

# Ignore files and directories matching the following patterns
build_ignore:
  - Dockerfile
  - Jenkinsfile
  - yamllint.yaml
