host: ec33017a.vmec.svl.ibm.com
user: omvsadm
python_path: /python/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3
environment:
  _BPXK_AUTOCVT: "ON"
  _CEE_RUNOPTS: "'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"
  _TAG_REDIR_ERR: txt
  _TAG_REDIR_IN: txt
  _TAG_REDIR_OUT: txt
  LANG: C
  ZOAU_ROOT: "/zoau/v1.2.0f"
  ZOAU_HOME: "/zoau/v1.2.0f"
  LIBPATH: "/zoau/v1.2.0f/lib:/python/usr/lpp/IBM/cyp/v3r8/pyz/lib:/lib:/usr/lib:."
  ZOAUTIL_DIR: "/zoau/v1.2.0f"
  PYTHONPATH: "/zoau/v1.2.0f/lib"
  PATH: "/zoau/v1.2.0f/bin:/python/usr/lpp/IBM/cyp/v3r8/pyz/bin/:/bin:.:/var/bin:/usr/lpp/java/J8.0/bin"
  STEPLIB: IMSTESTL.IMS1.SDFSRESL #'IMSBLD.I15RTSMM.COMRESL1'
extra_args:
    JOB_CARD: |-
      //ANSIBLE JOB 'testing',
      //  CLASS=H,MSGLEVEL=(1,1),REGION=0M,
      //  MSGCLASS=H,NOTIFY=&SYSUID
