---
- name: "z/OS | Check ZOAU installation and version"
  ansible.builtin.command:
    cmd: "zoaversion -c"
  register: managed_zoaversion
  changed_when: false
  ignore_errors: true

- name: "z/OS | Gather Python version"
  ansible.builtin.command:
    cmd: "python3 --version"
  register: managed_python_version
  changed_when: false
  ignore_errors: true

- name: "z/OS | Gather system locale"
  ansible.builtin.command:
    cmd: "locale"
  register: managed_locale
  changed_when: false
  ignore_errors: true

- name: "z/OS | Gather environment variables"
  ansible.builtin.command:
    cmd: "env"
  register: managed_env
  changed_when: false
  ignore_errors: true

- name: "z/OS | Gather Ansible facts"
  ibm.ibm_zos_core.zos_gather_facts:
    gather_subset:
      - ipl
      - sys
      - cpu
      - iodf
  register: zos_facts
  ignore_errors: true

- name: "z/OS | List installed pip packages"
  ansible.builtin.command:
    cmd: "pip3 list"
  register: managed_pip_list
  changed_when: false
  ignore_errors: true

- name: "z/OS | Extract paths from environment variables"
  ansible.builtin.set_fact:
    zoau_home_path: >-
      {{ (managed_env.stdout_lines
         | select('match', '^ZOAU_HOME=')
         | first
         | default('=not_found')
         | split('='))[1] }}
    python_exe_path: >-
      {{ (managed_env.stdout_lines
         | select('match', '^_=.*python.*')
         | first
         | default('=not_found')
         | split('='))[1] }}
  when: managed_env.stdout_lines is defined

- name: "z/OS | Determine Python home from executable path"
  ansible.builtin.set_fact:
    python_home_path: "{{ (python_exe_path | ansible.builtin.dirname) | ansible.builtin.dirname }}"
  when: python_exe_path is defined and python_exe_path != 'not_found'

- name: "z/OS | Check ZOAU home mount status (df)"
  ansible.builtin.shell:
    cmd: "df -P \"{{ zoau_home_path }}\""
  register: managed_df_zoau
  changed_when: false
  ignore_errors: true
  when: zoau_home_path is defined and zoau_home_path != 'not_found'

- name: "z/OS | Check APF bits in ZOAU bin directory"
  ansible.builtin.shell:
    cmd: "ls -E \"{{ zoau_home_path }}/bin\""
  register: managed_bin_apf_bits
  changed_when: false
  ignore_errors: true
  when: zoau_home_path is defined and zoau_home_path != 'not_found'

- name: "z/OS | Check Python home mount status (df)"
  ansible.builtin.shell:
    cmd: "df -P \"{{ python_home_path }}\""
  register: managed_df_python
  changed_when: false
  ignore_errors: true
  when: python_home_path is defined and python_home_path != 'not_found'


- name: "z/OS | OPTIONAL: Gather operator command output"
  when: support_mode_gather_syslog
  block:
    - name: "Run MVS operator command (e.g., 'D A,L')"
      ibm.ibm_zos_core.zos_operator:
        cmd: "D A,L"
      register: managed_operator_output
      ignore_errors: true
  rescue:
    - name: "Note: Operator command failed"
      ansible.builtin.debug:
        msg: "The 'zos_operator' command failed."

# --- DISPLAY MANAGED NODE RESULTS ---

- name: "z/OS | --- RESULTS ---"
  ansible.builtin.debug:
    msg: "Starting z/OS managed node diagnostics display"

- name: "z/OS | ZOAU Version"
  ansible.builtin.debug:
    var: managed_zoaversion.stdout
  when: managed_zoaversion is defined

- name: "z/OS | Python Version (stdout)"
  ansible.builtin.debug:
    var: managed_python_version.stdout
  when: managed_python_version is defined and managed_python_version.stdout != ""

- name: "z/OS | Python Version (stderr)"
  ansible.builtin.debug:
    var: managed_python_version.stderr
  when: managed_python_version is defined and managed_python_version.stderr != ""

- name: "z/OS | Locale"
  ansible.builtin.debug:
    var: managed_locale.stdout_lines
  when: managed_locale is defined

- name: "z/OS | Environment"
  ansible.builtin.debug:
    var: managed_env.stdout_lines
  when: managed_env is defined

- name: "z/OS | Core Facts"
  ansible.builtin.debug:
    var: zos_facts.ansible_facts
  when: zos_facts is defined and zos_facts.ansible_facts is defined

- name: "z/OS | Pip List"
  ansible.builtin.debug:
    var: managed_pip_list.stdout_lines
  when: managed_pip_list is defined

- name: "z/OS | ZOAU Path Mount Status"
  ansible.builtin.debug:
    var: managed_df_zoau.stdout_lines
  when: managed_df_zoau is defined and managed_df_zoau.stdout_lines is defined

- name: "z/OS | ZOAU apf attributes"
  ansible.builtin.debug:
    var: managed_bin_apf_bits.stdout_lines
  when: managed_bin_apf_bits is defined and managed_bin_apf_bits.stdout_lines is defined

- name: "z/OS | Python Path Mount Status"
  ansible.builtin.debug:
    var: managed_df_python.stdout_lines
  when: managed_df_python is defined and managed_df_python.stdout_lines is defined

- name: "z/OS | operator_command_output"
  ansible.builtin.debug:
    var: managed_operator_output.content
  when: managed_operator_output is defined and managed_operator_output.content is defined

- name: "z/OS | Consolidate all results into one variable"
  ansible.builtin.set_fact:
    support_mode_managed_results:
      zoau_version: "{{ managed_zoaversion.stdout | default('N/A') }}"
      python_version_stdout: "{{ managed_python_version.stdout | default('N/A') }}"
      python_version_stderr: "{{ managed_python_version.stderr | default('N/A') }}"
      locale: "{{ managed_locale.stdout_lines | default('N/A') }}"
      environment: "{{ managed_env.stdout_lines | default('N/A') }}"
      zos_facts: "{{ zos_facts.ansible_facts | default('N/A') }}"
      pip_list: "{{ managed_pip_list.stdout_lines | default('N/A') }}"
      df_zoau_path: "{{ managed_df_zoau.stdout_lines | default('N/A') }}"
      zoau_bin_attributes: "{{ managed_bin_apf_bits.stdout_lines | default('N/A') }}"
      df_python_path: "{{ managed_df_python.stdout_lines | default('N/A') }}"
      operator_command_output: "{{ managed_operator_output.content | default('N/A', true) }}"

- name: "z/OS | Save managed node results to a YAML file on the controller"
  ansible.builtin.copy:
    dest: "{{ lookup('env', 'HOME') }}/support_mode_report_{{ inventory_hostname }}.yml"
    content: "{{ support_mode_managed_results | to_nice_yaml }}"
  delegate_to: localhost
  when: support_mode_managed_results is defined