---
- ansible.builtin.set_fact:
    ansible_callback_plugin: yaml

- name: "z/OS | Check zOAU installation and version"
  ansible.builtin.command:
    cmd: "zoaversion -c"
  register: managed_zoaversion
  changed_when: false
  ignore_errors: true

- name: "z/OS | Gather Python version"
  ansible.builtin.command:
    cmd: "python3 --version"
  register: managed_python_version
  changed_when: false
  ignore_errors: true

- name: "z/OS | Gather system locale"
  ansible.builtin.command:
    cmd: "locale"
  register: managed_locale
  changed_when: false
  ignore_errors: true

- name: "z/OS | Gather environment variables"
  ansible.builtin.command:
    cmd: "env"
  register: managed_env
  changed_when: false
  ignore_errors: true

- name: "z/OS | Gather Ansible facts"
  ibm.ibm_zos_core.zos_gather_facts:
    gather_subset:
      - ipl
      - sys
      - cpu
      - iodf
  register: zos_facts