objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    zos_apf:
      description: Add or remove libraries to Authorized Program Facility (APF)
      name: zos_apf
      namespace: ''
      version_added: 1.3.0
    zos_backup_restore:
      description: Backup and restore data sets and volumes
      name: zos_backup_restore
      namespace: ''
      version_added: 1.3.0
    zos_blockinfile:
      description: Manage block of multi-line textual data on z/OS
      name: zos_blockinfile
      namespace: ''
      version_added: 1.3.0
    zos_copy:
      description: Copy data to z/OS
      name: zos_copy
      namespace: ''
      version_added: 1.2.0
    zos_data_set:
      description: Manage data sets
      name: zos_data_set
      namespace: ''
      version_added: 1.3.0
    zos_encode:
      description: Perform encoding operations.
      name: zos_encode
      namespace: ''
      version_added: 1.1.0
    zos_fetch:
      description: Fetch data from z/OS
      name: zos_fetch
      namespace: ''
      version_added: 1.1.0
    zos_find:
      description: Find matching data sets
      name: zos_find
      namespace: ''
      version_added: 1.3.0
    zos_gather_facts:
      description: Gather z/OS system facts.
      name: zos_gather_facts
      namespace: ''
      version_added: 1.5.0
    zos_job_output:
      description: Display job output
      name: zos_job_output
      namespace: ''
      version_added: 1.0.0
    zos_job_query:
      description: Query job status
      name: zos_job_query
      namespace: ''
      version_added: 1.0.0
    zos_job_submit:
      description: Submit JCL
      name: zos_job_submit
      namespace: ''
      version_added: 1.0.0
    zos_lineinfile:
      description: Manage textual data on z/OS
      name: zos_lineinfile
      namespace: ''
      version_added: 1.2.0
    zos_mount:
      description: Mount a z/OS file system.
      name: zos_mount
      namespace: ''
      version_added: 1.4.0
    zos_mvs_raw:
      description: Run a z/OS program.
      name: zos_mvs_raw
      namespace: ''
      version_added: 1.1.0
    zos_operator:
      description: Execute operator command
      name: zos_operator
      namespace: ''
      version_added: 1.1.0
    zos_operator_action_query:
      description: Display messages requiring action
      name: zos_operator_action_query
      namespace: ''
      version_added: 1.1.0
    zos_ping:
      description: Ping z/OS and check dependencies.
      name: zos_ping
      namespace: ''
      version_added: 1.1.0
    zos_tso_command:
      description: Execute TSO commands
      name: zos_tso_command
      namespace: ''
      version_added: 1.1.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.5.0
