name: Report a bug
description: Request that a bug be reviewed. Complete all required fields.
title: "[Bug] Enter description"
labels: [Bug]
assignees:
  - IBMAnsibleHelper
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: There are no existing issues.
          required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Bug description
      description: Describe the bug you are experiencing.
      placeholder: |
        Verbosity is encouraged, the more you share the better for us to understand.
          1. Include the steps to reproduce
          2. Include playbook if applicable
          3. Include screen captures of applicable
          4. Include expected vs actual results if applicable
    validations:
      required: true
  - type: dropdown
    id: collection-version
    attributes:
      label: IBM z/OS Ansible core Version
      description: Which version of z/OS Ansible core collection are you using. If you are unsure, review the [documentation](https://ibm.github.io/z_ansible_collections_doc/faqs/faqs.html#how-do-i-update-a-collection-to-the-latest-version).
      multiple: false
      options:
        - v1.12.0
        - v1.12.0-beta.1
        - v1.11.0
        - v1.11.0-beta.1
        - v1.10.0
        - v1.10.0-beta.1
        - v1.9.0
        - v1.9.0-beta.1
        - v1.8.0 (default)
        - v1.7.0
        - v1.6.0
        - v1.5.0
        - v1.4.1
        - v1.3.6
        - v1.3.5
        - v1.3.3
        - v1.3.1
        - v1.3.0
      default: 8
    validations:
      required: true
  - type: dropdown
    id: zoau-version
    attributes:
      label: IBM Z Open Automation Utilities
      description: Which version of ZOAU are you using? Please review the supported dependencies in the release notes](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html).
      multiple: false
      options:
        - v1.3.4
        - v1.3.3
        - v1.3.2
        - v1.3.1
        - v1.3.0
        - v1.2.5 (default)
        - v1.2.4
        - v1.2.3
        - v1.2.2
        - v1.2.1
        - v1.2.0
        - v1.1.1
        - v1.0.3
      default: 5
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: IBM Enterprise Python
      description: Which version of IBM Enterprise Python are you using? Please review the supported dependencies in the release notes](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html).
      multiple: false
      options:
        - v3.13.x
        - v3.12.x
        - v3.11.x (default)
        - v3.10.x
        - v3.9.x
        - v3.8.x
      default: 2
    validations:
      required: true
  - type: dropdown
    id: ansible-version
    attributes:
      label: ansible-version
      description: What is the version of Ansible on the controller (`ansible --version`)?
      multiple: false
      options:
        - v2.17.x
        - v2.16.x (default)
        - v2.15.x
        - v2.14.x
      default: 1
    validations:
      required: true
  - type: dropdown
    id: zos-version
    attributes:
      label: z/OS version
      description: What is the version of z/OS on the managed node? Please review the supported dependencies in the release notes](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html).
      multiple: false
      options:
        - v3.1 (unsupported)
        - v2.5 (default)
        - v2.4
      default: 1
    validations:
      required: false
  - type: dropdown
    id: modules
    attributes:
      label: Ansible module
      description: Select which modules are being reported in this bug. You can select more than one.
      multiple: true
      options:
        - zos_apf
        - zos_archive
        - zos_backup_restore
        - zos_blockinfile
        - zos_copy
        - zos_data_set
        - zos_encode
        - zos_fetch
        - zos_find
        - zos_gather_facts
        - zos_job_output
        - zos_job_query
        - zos_job_submit
        - zos_lineinfile
        - zos_mount
        - zos_mvs_raw
        - zos_operator
        - zos_operator_action_query
        - zos_ping
        - zos_script
        - zos_tso_command
        - zos_unarchive
        - zos_volume_init
    validations:
      required: false
  - type: textarea
    id: issue-output
    attributes:
      label: Playbook verbosity output.
      description: Provide the command line output with debug and verbosity enabled.
      placeholder: |
        Insert the output using this form of the playbook command.
          - `ANSIBLE_DEBUG=1 ansible-playbook -i inventory your-playbook.yml -vvvv`
    validations:
      required: false
  - type: textarea
    id: ansible-cfg
    attributes:
      label: Ansible configuration.
      description: Show the current **ansible.cfg** settings.
      placeholder: |
        Insert for this command: `ansible-config view`
      render: YAML
    validations:
      required: false
  - type: textarea
    id: ansible-inventory
    attributes:
      label: Contents of the inventory
      description: Provide the contents of the inventory.
      render: YAML
    validations:
      required: false
  - type: textarea
    id: ansible-vars
    attributes:
      label: Contents of `group_vars` or `host_vars`
      description: Provide the contents of `group_vars` or `host_vars`
      render: YAML
    validations:
      required: false

