name: Report a documentation issue
description: Request that documentation be reviewed. Complete all required fields.
title: "[Documentation] <title> "
labels: [Documentation]
assignees:
  - IBMAnsibleHelper
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: There are no existing issues.
          required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Documentation issue description
      description: Describe the documentation issue.
      placeholder: |
        Verbosity is encouraged, the more you share the better for us to understand.
          1. Include links to the page you are referring to if applicable
          2. Include reproduction steps if applicable
          3. Include any additional information that will help us
          4. Include screen captures of applicable
          5. Include browser or shell if applicable
    validations:
      required: true
  - type: dropdown
    id: collection-version
    attributes:
      label: IBM z/OS Ansible core Version
      description: Which version of z/OS Ansible core collection are you using. If you are unsure, review the [documentation](https://ibm.github.io/z_ansible_collections_doc/faqs/faqs.html#how-do-i-update-a-collection-to-the-latest-version).
      multiple: false
      options:
        - v1.16.0-beta.1
        - v1.15.0
        - v1.15.0-beta.1
        - v1.14.1
        - v1.14.0
        - v1.14.0-beta.1
        - v1.13.1
        - v1.13.0
        - v1.13.0-beta.1
        - v1.12.0
        - v1.12.0-beta.1
        - v1.11.1
        - v1.11.0
        - v1.11.0-beta.1
        - v1.10.0
        - v1.10.0-beta.1
      default: 6
    validations:
      required: false
  - type: dropdown
    id: modules
    attributes:
      label: Ansible module
      description: Select which modules are being reported in this bug. You can select more than one.
      multiple: true
      options:
        - zos_apf
        - zos_archive
        - zos_backup_restore
        - zos_blockinfile
        - zos_copy
        - zos_data_set
        - zos_encode
        - zos_fetch
        - zos_find
        - zos_gather_facts
        - zos_job_output
        - zos_job_query
        - zos_job_submit
        - zos_lineinfile
        - zos_mount
        - zos_mvs_raw
        - zos_operator
        - zos_operator_action_query
        - zos_ping
        - zos_replace
        - zos_script
        - zos_started_task
        - zos_stat
        - zos_tso_command
        - zos_unarchive
        - zos_volume_init
        - zos_zfs_resize
    validations:
      required: false
