name: Enabler task
description: |
    Identify a development task that does not correspond to other git issue types, eg this could be a pipeline task.
    Complete all required fields.
title: "[Enabler] <title> "
labels: [Enabler]
assignees:
  - IBMAnsibleHelper
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: There are no existing issues.
          required: true
  - type: dropdown
    id: modules
    attributes:
      label: Ansible module
      description: Select which modules are being reported for this task. You can select more than one.
      multiple: true
      options:
        - zos_apf
        - zos_backup_restore
        - zos_blockinfile
        - zos_copy
        - zos_data_set
        - zos_encode
        - zos_fetch
        - zos_find
        - zos_gather_facts
        - zos_job_output
        - zos_job_query
        - zos_job_submit
        - zos_lineinfile
        - zos_mount
        - zos_mvs_raw
        - zos_operator
        - zos_operator_action_query
        - zos_ping
        - zos_script
        - zos_tso_command
    validations:
      required: false
  - type: textarea
    id: issue-description
    attributes:
      label: Enabler description
      description: Describe the task, this is the equivalent of a agile story.
      placeholder: Verbosity is encouraged, the more you share the better for us to understand.
    validations:
      required: true
