name: Request an enhancement or new feature
description: Request a new feature or an enhancement. Complete all required fields.
title: "[Enhancement] <title> "
labels: [Enhancement]
assignees:
  - IBMAnsibleHelper
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: There are no existing issues.
          required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Enhancement or feature description
      description: Describe the enhancement or feature you are requesting.
      placeholder: Verbosity is encouraged, the more you share the better for us to understand.
    validations:
      required: true
  - type: dropdown
    id: modules
    attributes:
      label: Ansible module
      description: Select which modules are being reported in this bug. You can select more than one.
      multiple: true
      options:
        - zos_apf
        - zos_archive
        - zos_backup_restore
        - zos_blockinfile
        - zos_copy
        - zos_data_set
        - zos_encode
        - zos_fetch
        - zos_find
        - zos_gather_facts
        - zos_job_output
        - zos_job_query
        - zos_job_submit
        - zos_lineinfile
        - zos_mount
        - zos_mvs_raw
        - zos_operator
        - zos_operator_action_query
        - zos_ping
        - zos_replace
        - zos_script
        - zos_stat
        - zos_tso_command
        - zos_unarchive
        - zos_volume_init
        - zos_zfs_resize
    validations:
      required: true

