name: Request an enhancement or new feature
description: Request a new feature or that content be enhanced.
title: "[Enhancement] <title> "
labels: [Enhancement]
assignees:
  - IBMAnsibleHelper
body:
  - type: markdown
    attributes:
      value: |
        Before requesting an enhancement or feature, please review existing isssues to avoid duplication.
        ---
  - type: textarea
    id: issue-description
    attributes:
      label: Enhancement or featture description
      description: Describe the enhancement or feature you are requesting.
      placeholder: Verbosity is encouraged, the more you share the better for us to understand.
    validations:
      required: true
  - type: dropdown
    id: modules
    attributes:
      label: Ansible module
      description: Select which modules are being reported in this enhancement or feature. You can select more than one.
      multiple: true
      options:
        - zos_apf
        - zos_backup_restore
        - zos_blockinfile
        - zos_copy
        - zos_data_set
        - zos_encode
        - zos_fetch
        - zos_find
        - zos_gather_facts
        - zos_job_output
        - zos_job_query
        - zos_job_submit
        - zos_lineinfile
        - zos_mount
        - zos_mvs_raw
        - zos_operator
        - zos_operator_action_query
        - zos_ping
        - zos_tso_command
    validations:
      required: false
