name: Request a new module
description: Request a new module be added to the collection. Complete all required fields.
title: "[Module] <title> "
labels: [Module]
assignees:
  - IBMAnsibleHelper
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: There are no existing issues.
          required: true
  - type: textarea
    id: issue-description
    attributes:
      label: New module description
      description: Describe the new module you are requesting.
      placeholder: Verbosity is encouraged, the more you share the better for us to understand.
    validations:
      required: true
  - type: textarea
    id: user-story
    attributes:
      label: User story
      description: Write a user story with emphasis on the persona, for example sysadmin.
      placeholder: |
        Verbosity is encouraged, the more you share the better for us to understand.
        User stories take this form:
          - As a < type of user >, I want < some goal > so that < some reason >.
        Examples:
          - As a z/OS System Admin, I can grow zFS aggregates with Ansible so that my data sets don't fill up.
          - As a Junior developer, I want to be able to zip and unzip arives using Ansible, so that I don't have to perform operations elsewhere.
    validations:
      required: false
