#!/bin/sh
# ==============================================================================
# Copyright (c) IBM Corporation 2022, 2023
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

################################################################################
# Global vars
################################################################################
zoau_version=""
python_version=""
python_path=""
bash_enabled=false

################################################################################
# zoau case match
################################################################################
zoau_choice () {
	case "$1" in
        [a]* ) zoau_version="v1.2.0";;
        [b]* ) zoau_version="v1.0.0-ga";;
        [c]* ) zoau_version="v1.0.1-ga";;
        [d]* ) zoau_version="v1.0.1-ptf1";;
        [e]* ) zoau_version="v1.0.1-ptf2";;
        [f]* ) zoau_version="v1.0.2-ga";;
        [g]* ) zoau_version="v1.0.3-ga5";;
        [h]* ) zoau_version="v1.0.3-ptf2";;
        [i]* ) zoau_version="v1.1.0-spr";;
        [j]* ) zoau_version="v1.1.0-spr5";;
        [k]* ) zoau_version="v1.1.0-spr7";;
        [l]* ) zoau_version="v1.1.0-ga";;
        [m]* ) zoau_version="v1.1.1-ptf1";;
        [n]* ) zoau_version="v1.2.0f";;
        [o]* ) zoau_version="v1.2.1";;
        [p]* ) zoau_version="v1.2.1-rc1";;
        [q]* ) zoau_version="v1.2.1g";;
        [r]* ) zoau_version="v1.2.1h";;
        [s]* ) zoau_version="v1.2.2";;
        [t]* ) zoau_version="latest";;
		* ) echo ""
			usage
			;;
	esac
}

################################################################################
# zoau case match
################################################################################
python_choice () {
	case $1 in
		[1]* ) python_version="3.8";
			   python_path="/python3/usr/lpp/IBM/cyp/v3r8/pyz";;
		[2]* ) python_version="3.9";
			   python_path="/python2/usr/lpp/IBM/cyp/v3r9/pyz";;
		[3]* ) python_version="3.10";
			   python_path="/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz";;
		[4]* ) python_version="3.11";
			   python_path="/allpython/3.11-ga/usr/lpp/IBM/cyp/v3r11/pyz";;
		   *) echo "";usage;;
	esac
}

################################################################################
# zoau case match
################################################################################
bash_choice() {
	case "$1" in
    	[b]* ) bash_enabled=true;;
           * ) echo "";usage;;
     esac
}
################################################################################
# User input for Python
################################################################################
usage () {
	echo ""
    echo "Usage: $0 [abcdefghijklmn] [123] b"
    echo "ZOAU Choices:"
    echo "\ta) ZOAU /zoau/v1.2.0"
    echo "\tb) ZOAU /zoau/v1.0.0-ga"
    echo "\tc) ZOAU /zoau/v1.0.1-ga"
    echo "\td) ZOAU /zoau/v1.0.1-ptf1"
    echo "\te) ZOAU /zoau/v1.0.1-ptf2"
    echo "\tf) ZOAU /zoau/v1.0.2-ga"
    echo "\tg) ZOAU /zoau/v1.0.3-ga5"
    echo "\th) ZOAU /zoau/v1.0.3-ptf2"
    echo "\ti) ZOAU /zoau/v1.1.0-spr"
    echo "\tj) ZOAU /zoau/v1.1.0-spr5"
    echo "\tk) ZOAU /zoau/v1.1.0-spr7"
    echo "\tl) ZOAU /zoau/v1.1.0-ga"
    echo "\tm) ZOAU /zoau/v1.1.1-ptf1"
    echo "\tn) ZOAU /zoau/v1.2.0f"
    echo "\to) ZOAU /zoau/v1.2.1"
    echo "\tp) ZOAU /zoau/v1.2.1-rc1"
    echo "\tq) ZOAU /zoau/v1.2.1g"
    echo "\tr) ZOAU /zoau/v1.2.1h"
    echo "\ts) ZOAU /zoau/v1.2.2"
    echo "\tt) ZOAU /zoau/latest"
	echo ""
	echo "Python Choices:"
	echo "\t1) Python 3.8"
	echo "\t2) Python 3.9"
	echo "\t3) Python 3.10"
	echo "\t4) Python 3.11"
	echo ""
	echo "Bash shell"
	echo "\tb) 'b' to enable bash shell"
}

################################################################################
# Message to user
################################################################################
print_choices () {
	echo "Using ZOAU version="$zoau_version
	echo "Using python version="$python_version
	echo "Bash = ${bash_enabled}"
}

################################################################################
# Configure all exports
################################################################################
set_exports (){

	export PATH=/bin:.

	################################################################################
	# Set the ported tools directory on the EC, see the tools you can use, eg:
	# vim, bash, etc
	################################################################################
	export TOOLS_DIR=/usr/lpp/rsusr/ported
	export PATH=$PATH:$TOOLS_DIR/bin

	################################################################################
	# Set the editor to VI
	################################################################################
	export TERM=xterm

	################################################################################
	# Standard exports used in EBCDIC/ASCII conversion needed by tools like pyz/zoau
	################################################################################
	export _BPXK_AUTOCVT='ON'
	export _CEE_RUNOPTS='FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'
	export _TAG_REDIR_ERR=txt
	export _TAG_REDIR_IN=txt
	export _TAG_REDIR_OUT=txt
	export LANG=C

	################################################################################
	# Set Java
	################################################################################
	export JAVA_HOME=/usr/lpp/java170/J7.0

	################################################################################
	# Configure Python
	################################################################################
	export PYTHON_HOME=$python_path
	export PYTHON=$PYTHON_HOME/bin
	export LIBPATH=$PYTHON_HOME/lib:$LIBPATH

	################################################################################
	# ZOAU 1.0.2 or or earlier ueses ZOAU_ROOT and not ZOAU_HOME
	################################################################################
	export ZOAU_HOME=/zoau/${zoau_version}
	export PATH=$ZOAU_HOME/bin:$PATH:$PYTHON:$JAVA_HOME/bin:$TOOLS_DIR/bin
	export MANPATH=$MANPATH:$TOOLS_DIR/man
	export ZOAU_ROOT=${ZOAU_HOME}
	export PYTHONPATH=${ZOAU_HOME}/lib/:${PYTHONPATH}
	export LIBPATH=${ZOAU_HOME}/lib:${LIBPATH}

	################################################################################
	# Custom terminal configurations
	################################################################################
	# Append home directory to the current path
	export PATH=$PATH:$HOME:

	# Set the prompt to display your login name & current directory
	export PS1='[ $LOGNAME':'$PWD':' ]'

	################################################################################
	# Run bash shell:
	# I have have seen many issues using this version of bash to edit files on the
	# EC, for example of you edit your .profile with VI under BASH, it will render
	# unreable, for times I have to edit, I type exit it defaults be back into
	# the zos_ssh shell which does not have any issues with VI or editing files.
	# I generally use bash only for history and running commands.
	################################################################################
	if [ "{$bash_enabled}" = true ]; then
	   	bash;
	fi

	alias python="python3"
	alias pip="pip3"
}
################################################################################
# Main
################################################################################
# User enters choices for zoau, python and bash
if [ $# -eq 3 ];then
	zoau_choice $1
	python_choice $2
	bash_choice $3
	print_choices
	set_exports

# User enters choices for zoau and python, bash defaults to false
elif [ $# -eq 2 ];then
	bash_enabled=false
	zoau_choice $1
	python_choice $2
	print_choices
	set_exports

# User enters choice for zoau, python defaults to 3.8 and bash to false
elif [ $# -eq 1 ]; then
	zoau_choice $1
	python_choice 1
	bash_enabled=false
	print_choices
	set_exports
else
	usage
fi
