name: AC Ansible sanity

on:
  pull_request:
    branches:
      - dev
      - staging*
    
jobs:
  ansible-sanity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: .ansible/collections/ansible_collections/ibm/ibm_zos_core

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Set up venv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        mkdir .ansible/collections/ansible_collections/ibm/ibm_zos_core/venv
        virtualenv .ansible/collections/ansible_collections/ibm/ibm_zos_core/venv/venv-2.16

    - name: Install dependencies
      run: |
        source .ansible/collections/ansible_collections/ibm/ibm_zos_core/venv/venv-2.16/bin/activate
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run ac-sanity
      run: |
        source .ansible/collections/ansible_collections/ibm/ibm_zos_core/venv/venv-2.16/bin/activate
        cd .ansible/collections/ansible_collections/ibm/ibm_zos_core
        ./ac --ac-sanity
