name: AC Ansible sanity

on:
  pull_request:
    branches:
      - dev
      - staging*
    paths-ignore:
      - '**.tar.gz'
      - 'pycache/'
      - '.ansible-lint'
      - 'cache/'
      - '.DS_Store'
      - '.git/'
      - '.github/'
      - '.gitignore'
      - '.python-version'
      - '.pytest_cache/'
      - '.vscode/'
      - 'Jenkinsfile'
      - 'ac'
      - 'ansible.cfg'
      - 'changelogs/'
      - 'collections/'
      - 'docs/'
      - 'scripts/'
      - 'test_config.yml'
      - 'tests/*.ini'
      - 'tests/*.py'
      - 'tests/.pytest_cache'
      - 'tests/pycache'
      - 'tests/functional'
      - 'tests/helpers'
      - 'tests/requirements.txt'
      - 'tests/unit'
      - 'tests/sanity/ignore-2.9'
      - 'tests/sanity/ignore-2.10'
      - 'tests/sanity/ignore-2.11'
      - 'tests/sanity/ignore-2.12'
      - 'tests/sanity/ignore-2.13'
      - 'venv*'

jobs:
  ansible-sanity:
    runs-on: ubuntu-latest
    env:
      branch: ${{ github.event.pull_request.head.ref }}

    steps:
#    - name: Checkout repository
#      run:
#        pwd
#        cd .ansible/collections/ansible_collections/ibm/ibm_zos_core/
#        git clone https://github.com/ansible-collections/ibm_zos_core.git
#        git checkout origin/"$branch"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
  
    - name: Set up venv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        mkdir venv
        virtualenv venv/venv-2.16

    - name: Install dependencies
      run: |
        source venv/venv-2.16/bin/activate
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run ac-sanity
      run: |
        source venv/venv-2.16/bin/activate
        ./ac --ac-build
        ./ac --ac-sanity
