name: AC Ansible sanity

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - dev
      - staging*
    paths-ignore:
      - '**.tar.gz'
      - 'pycache/**'
      - '.ansible-lint'
      - 'cache/**'
      - '.DS_Store'
      - '.git/**'
      - '.github/**'
      - '.gitignore'
      - '.python-version'
      - '.pytest_cache/**'
      - '.vscode/**'
      - 'Jenkinsfile'
      - 'ac'
      - 'ansible.cfg'
      - 'changelogs/**'
      - 'collections/**'
      - 'docs/**'
      - 'scripts/**'
      - 'test_config.yml'
      - 'tests/*.ini'
      - 'tests/*.py'
      - 'tests/.pytest_cache'
      - 'tests/pycache'
      - 'tests/functional'
      - 'tests/helpers'
      - 'tests/requirements.txt'
      - 'tests/unit'
      - 'tests/sanity/ignore-*'
      - 'venv*'

jobs:
  ansible-sanity:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      branch: ${{ github.event.pull_request.head.ref }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
  
    - name: Set up venv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        mkdir venv
        virtualenv venv/venv-2.18

    - name: Install dependencies
      run: |
        source venv/venv-2.18/bin/activate
        python -m pip install --upgrade pip
        pip install "ansible-core>=2.18,<2.19"

    - name: Run ac-sanity
      run: |
        source venv/venv-2.18/bin/activate
        ./ac --ac-build
        ./ac --ac-sanity
