name: AC Ansible sanity

on:
  pull_request:
    branches:
      - dev
      - staging*
    
jobs:
  ansible-sanity:
    runs-on: ubuntu-latest
    env:
      branch: ${{ github.event.pull_request.head.ref }}

    steps:
#    - name: Checkout repository
#      run:
#        pwd
#        cd .ansible/collections/ansible_collections/ibm/ibm_zos_core/
#        git clone https://github.com/ansible-collections/ibm_zos_core.git
#        git checkout origin/"$branch"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: $branch


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
  
    - name: Set up venv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        cd .ansible/collections/ansible_collections/ibm/ibm_zos_core/
        mkdir venv
        virtualenv venv/venv-2.16

    - name: Install dependencies
      run: |
        cd .ansible/collections/ansible_collections/ibm/ibm_zos_core
        source venv/venv-2.16/bin/activate
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run ac-sanity
      run: |
        cd .ansible/collections/ansible_collections/ibm/ibm_zos_core
        source venv/venv-2.16/bin/activate
        ./ac --ac-build
        ./ac --ac-sanity
