name: Bandit Scan

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - dev
      - staging*
    paths:
      - 'plugins/**'
      - 'ac'

jobs:
  bandit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Set up venv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run ac-bandit
      run: |
        source venv/bin/activate
        python3 -m bandit -r plugins/* -l
