name: AC Bandit

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - dev
      - staging*
    
jobs:
  bandit:
    if: ! github.event.pull_request.draft
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Set up venv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        mkdir venv
        virtualenv venv/venv-2.16

    - name: Install dependencies
      run: |
        source venv/venv-2.16/bin/activate
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run ac-bandit
      run: |
        source venv/venv-2.16/bin/activate
        ./ac --ac-bandit --level l
