name: AC Check Changelog

on:
  pull_request:
    branches:
      - dev
      - staging*
    paths-ignore:
      - '**.tar.gz'
      - 'pycache/**'
      - '.ansible-lint'
      - 'cache/**'
      - '.DS_Store'
      - '.git/**'
      - '.github/**'
      - '.gitignore'
      - '.python-version'
      - '.pytest_cache/**'
      - '.vscode/**'
      - 'Jenkinsfile'
      - 'ac'
      - 'ansible.cfg'
      - 'collections/**'
      - 'docs/**'
      - 'scripts/**'
      - 'test_config.yml'
      - 'tests/*.ini'
      - 'tests/*.py'
      - 'tests/.pytest_cache'
      - 'tests/pycache'
      - 'tests/functional'
      - 'tests/helpers'
      - 'tests/requirements.txt'
      - 'tests/unit'
      - 'tests/sanity/ignore-*'
      - 'venv*'

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    env:
        PR_BASE: ${{ github.event.pull_request.base.ref }}
        PR_HEAD: ${{ github.event.pull_request.head.ref }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Set up venv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        mkdir venv
        virtualenv venv/venv-2.16

    - name: Run ac-check-changelog
      run: |
        ./ac --ac-check-changelog --base "$PR_BASE" --head origin/"$PR_HEAD"
