name: AC Check Changelog

on:
  pull_request:
    branches:
      - dev
      - staging*

    
jobs:
  check-changelog:
    runs-on: ubuntu-latest
    env:
        PR_BASE: ${{ github.event.pull_request.base.ref }}
        PR_HEAD: ${{ github.event.pull_request.head.ref }}    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Set up venv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        mkdir venv
        virtualenv venv/venv-2.16

    - name: Run ac-check-changelog
      run: |
        ./ac --ac-check-changelog --base "$PR_BASE" --head origin/"$PR_HEAD"