name: Module Doc Check

on:
  pull_request:
    paths:
      - 'plugins/modules/*'
    branches:
      - dev
      - staging*

jobs:
  module-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up venv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install ansible==11.9.0
          pip install ansible-doc-extractor

      - name: Run ac-module-doc
        run: |
          source venv/bin/activate
          export ANSIBLE_LIBRARY=/home/runner/work/ibm_zos_core/ibm_zos_core/plugins/modules/
          rm -rf ibm-ibm_zos_core-*.tar.gz
          ansible-galaxy collection build
          ansible-galaxy collection install -f ibm-ibm_zos_core-*
          cd docs && make clean && make module-doc
