name: Ansible Test

on:
  pull_request:

  workflow_dispatch:

jobs:
  ansible-test:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible test
      run: |
        collection_name=$(ansible-galaxy collection build | awk -F/ '{print $NF}')
        ansible-galaxy collection install
        cd ~/.ansible/collections/ansible_collections/ibm/ibm_zos_core/&& ansible-test sanity $collection_name
