name: Antsibull Changelog Lint

on:
  pull_request:
    paths:
    - 'changelogs/fragments/*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Set up venv
      run: |
        python -m pip install --upgrade pip
	pip install virtualenv
	virtualenv venv

    - name: Install dependencies
      run: |
	source venv/bin/activate
        pip install antsibull-changelog

    - name: Run ac-changelog
      run: |
        ./ac --ac-changelog --command lint
